version: '3.8'
services:
  postgres:
    container_name: food-explorer
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: food-explorer
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
  cache:
    container_name: food-explorer-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data